import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
import {createNativeSceneGameEditor} from '../scripts/native-scene-game-editor.mjs';
class Element{constructor(){this.value='';this.children=[];this.checked=false;this.disabled=false;this.textContent='';}replaceChildren(...items){this.children=items;this.value=items[0]?.value??'';}append(...items){this.children.push(...items);}}
const html=await readFile(new URL('../scripts/native-scene-game-editor.html',import.meta.url),'utf8');const nodes=new Map();
for(const match of html.matchAll(/<[^>]*id="(nativeSceneGame[^"]+)"[^>]*>/g)){assert(!nodes.has(match[1]));const item=new Element();item.value=match[0].match(/value="([^"]*)"/)?.[1]??'';nodes.set(match[1],item);}
nodes.set('nativeSceneJobs',new Element());nodes.get('nativeSceneJobs').value='scene1';
const el=name=>{assert(nodes.has('nativeSceneGame'+name));return nodes.get('nativeSceneGame'+name);};
const doc={getElementById:id=>nodes.get(id),createElement:()=>new Element()};
const metadata={scene_job:'scene1',source_result_sha256:'a'.repeat(64),times_s:[0,1/480,.8,1,2],actors:{A:{glb_sha256:'b'.repeat(64),animation_index:0,joints:[{node:0,name:'Mapped root'},{node:4,name:'Custom joint'}]},B:{glb_sha256:'c'.repeat(64),animation_index:0,joints:[{node:3,name:'Other root'}]}}};
let waiting=null,posted=null,saved=null,jobs={jobs:[]},review={status:'processing',stage:'root-contact-tracks',downloads:[]};
const api=async url=>{if(url.startsWith('/api/native-scene-game-source?'))return waiting||structuredClone(metadata);if(url==='/api/native-scene-game-jobs')return structuredClone(jobs);if(url.startsWith('/api/native-scene-game-review?'))return structuredClone(review);throw Error(url);};
const editor=createNativeSceneGameEditor({document:doc,api,post:async(url,payload)=>{assert.equal(url,'/api/native-scene-game-assets');posted=structuredClone(payload);jobs={jobs:[{id:'game1'}]};return {id:'game1'};},download:value=>saved=value});
assert.throws(()=>editor.snapshot(),/Bind/);await el('Bind').onclick();assert.throws(()=>editor.snapshot(),/Choose the root/);
const rootSelect=name=>el('Roots').children[Object.keys(metadata.actors).indexOf(name)].children[0];
rootSelect('A').value='0';rootSelect('B').value='3';el('Time').value=String(1/480);await el('Add').onclick();
assert.equal(editor.snapshot().request.markers[0].time_s,1/480);assert.equal(editor.snapshot().request.markers[0].confirmed,false);
el('MarkerId').value='event-2';el('MarkerName').value='release';el('Actor').value='B';el('Time').value='.8';el('Confirmed').checked=true;await el('Add').onclick();
assert.equal(editor.snapshot().request.markers[1].confirmed,true);assert.deepEqual(editor.snapshot().request.actors,{A:{root_node:0},B:{root_node:3}});
el('Time').value='0.00208333333333333';el('MarkerId').value='rounded';await el('Add').onclick();assert.match(el('Status').textContent,/exact audited time/);assert.equal(editor.snapshot().request.markers.length,2);
await el('Save').onclick();assert.deepEqual(saved,editor.snapshot());await el('Build').onclick();assert.deepEqual(posted,saved);assert.equal(el('Build').disabled,false);assert.equal(el('Jobs').value,'game1');
await el('Review').onclick();assert.match(el('Results').children[0].textContent,/root-contact-tracks/);
review={status:'complete',samples:1101,root_samples_pass:true,scene_sampled_conditions_pass:false,event_helper_dispatch_verified:true,downloads:[{url:'/files/native-scene-game-jobs/game1/game-assets.zip',label:'game-assets.zip'}]};await el('Review').onclick();
assert.match(el('Results').children[0].textContent,/Scene conditions: fail/);assert.match(el('Results').children[0].textContent,/motion-quality approval remain separate/);assert.equal(el('Results').children[1].href,review.downloads[0].url);
assert.equal(nodes.get('nativeSceneJobs').value,'scene1');
nodes.get('nativeSceneJobs').value='scene2';posted=null;await el('Build').onclick();assert.equal(posted,null);assert.match(el('Status').textContent,/Bind the selected/);
nodes.get('nativeSceneJobs').value='scene1';let resolve;waiting=new Promise(r=>resolve=r);const pending=el('Bind').onclick();nodes.get('nativeSceneJobs').value='scene2';resolve(metadata);await pending;assert.match(el('Status').textContent,/selection changed/);assert.throws(()=>editor.snapshot(),/Bind/);
waiting=null;nodes.get('nativeSceneJobs').value='scene1';await el('Bind').onclick();assert.equal(el('Markers').children.length,0);assert.equal(rootSelect('A').value,'');
rootSelect('A').value='4';rootSelect('B').value='3';el('Time').value='0';el('MarkerId').value='start';await el('Add').onclick();assert.equal(editor.snapshot().request.actors.A.root_node,4);
el('Markers').children[0].children[0].onclick();assert.equal(editor.snapshot().request.markers.length,0);
review={status:'failed',error:'Retained fixture failure',downloads:[]};await el('Review').onclick();assert.match(el('Results').children[0].textContent,/Retained fixture failure/);
console.log('Explicit root choices, exact native times, marker confirmation, stale scene isolation and failed-result UI passed offline.');
const bootstrap=await readFile(new URL('../scripts/character-studio.js',import.meta.url),'utf8'),context={};
vm.runInNewContext(bootstrap.slice(0,bootstrap.indexOf('void (async function characterStudio')),context);
const message=new Element();
assert.equal(await context.initializeOptionalRigEditor(async()=>{throw Error('Module 404 from an older backend');},message,'Game-track editor'),false);
assert.match(message.textContent,/Module 404/);assert.match(message.textContent,/Restart Studio/);
let loaded=false;assert.equal(await context.initializeOptionalRigEditor(async()=>{loaded=true;},message,'Game-track editor'),true);assert(loaded);
console.log('Unavailable optional scene modules cannot abort remaining character-editor initialization.');
