import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createNativeTransitionFitEditor,stagedBridgeCorrection} from '../scripts/native-transition-fit-editor.mjs';
class Element{constructor(){this.value='';this.children=[];this.disabled=false;this.textContent='';}replaceChildren(...v){this.children=v;this.value=v[0]?.value??'';}append(...v){this.children.push(...v);}}
const html=await readFile(new URL('../scripts/native-transition-fit-editor.html',import.meta.url),'utf8'),nodes=new Map();
for(const m of html.matchAll(/<[^>]*id="(nativeTransitionFit[^"]+)"[^>]*>/g)){const e=new Element();e.value=m[0].match(/value="([^"]*)"/)?.[1]??'';e.disabled=m[0].includes('disabled');nodes.set(m[1],e);}
const document={getElementById:id=>nodes.get(id),createElement:()=>new Element()},el=n=>nodes.get('nativeTransitionFit'+n),h='a'.repeat(64),clip='b'.repeat(64),job='fit1',prefix='/files/native-transition-fit-jobs/fit1/';
const source={folder:'saved/assembly',result_sha256:h},tracks=[{node:1,path:'rotation',name:'Arm',eligible:true,tangent_guards:[[.4,.425],[.575,.6]]},{node:0,path:'translation',name:'Root',eligible:false,reason:'No interior keys'}];
const catalog={schema:'strep-studio-native-transition-fit-catalog-v1',source,actors:{A:{tracks},B:{tracks}},objects:['box'],duration_s:1.2,bridge_interval_s:[.4,.6],times_s:[0,.4,.5,.6,1.2],floor:null,source_checks:{contacts:false,objects:true},quality_approved:false,release_approved:false};
const request={schema:'strep-studio-native-transition-fit-v1',source,label:'Corrected transition',actors:{A:{window_s:[.4,.6],protected_s:[],knots_s:[.4,.5,.6],tracks:[{node:1,path:'rotation',maximum_change:5}],maximum_joint_displacement_m:.03}},geometry:{clock:{mode:'explicit',times_s:catalog.times_s},limits:{penetration_m:.00001,depth_resolution_m:1e-6,surface_tolerance_m:1e-8},planes:{}},iterations:1,maximum_pose_vertex_queries:1000000,resume_from:null};
const draft={schema:'strep-studio-native-scene-v1',scene:{schema:'strep-native-scene-contacts-v1',duration_s:1.2,actors:{A:{glb:prefix+'candidate/actors/0.glb',sha256:clip,animation_index:4},B:{glb:prefix+'candidate/actors/1.glb',sha256:clip,animation_index:4}},objects:{box:{}},contacts:[{}]},geometry:request.geometry,object_edit:null};
const game={schema:'strep-native-scene-game-tracks-v1',actors:{A:{root_node:0},B:{root_node:0}},markers:[{id:'cue',actor:'A',time_s:.5,confirmed:false}]};
const files=['stage-draft.json','stage-game-tracks.json','candidate/result.json','candidate/contacts-audit.json','candidate/geometry.json','candidate/fit/result.json','candidate/permissions.json','candidate/geometry-policy.json','candidate/fit/source-rate-caps.npz','candidate/tracks/root-motion.json','candidate/tracks/events.json','candidate/actors/0.glb','candidate/actors/1.glb'];
const review={id:job,status:'complete',result_sha256:'c'.repeat(64),candidate_result_sha256:'d'.repeat(64),candidate_binding:{folder:'native-transition-fit-jobs/fit1/candidate',result_sha256:'d'.repeat(64)},original_animation_counts:{A:4,B:4},draft,game_tracks:game,authoring_request:request,
 checks:{native_motion_and_contacts:false,native_contact_audit:false,actor_transition_conditions:true,whole_scene_geometry:false},all_declared_samples_pass:false,original_selected:true,studio_selection_changed:false,native_roots_only:true,quality_approved:false,training_admitted:false,release_approved:false,engine_playback_verified:false,
 files_sha256:Object.fromEntries(files.map(n=>[n,n.endsWith('.glb')?clip:h])),downloads:files.map(label=>({label,url:prefix+label,sha256:label.endsWith('.glb')?clip:h}))};
assert.deepEqual(stagedBridgeCorrection(review).draft,draft);
for(const mutate of [r=>r.quality_approved=true,r=>r.native_roots_only=1,r=>r.checks.native_contact_audit=0,r=>delete r.checks.native_contact_audit,r=>r.all_declared_samples_pass=true,r=>r.draft.scene.actors.A.animation_index=3,r=>r.game_tracks.markers[0].confirmed=true,r=>r.downloads.pop(),r=>r.files_sha256['candidate/fit/source-rate-caps.npz']='0'.repeat(64),r=>r.downloads[0].url='https://bad.test',r=>r.candidate_binding.result_sha256=h]){const r=structuredClone(review);mutate(r);assert.throws(()=>stagedBridgeCorrection(r));}
let current={schema:'existing'},queued=null,waiting=null,posts=[],applyCount=0;
const editor=createNativeTransitionFitEditor({document,api:async url=>waiting??structuredClone(url.endsWith('jobs')?{jobs:[{id:job,status:'complete'}]}:review),post:async(url,p)=>{posts.push([url,structuredClone(p)]);return waiting??structuredClone(url.endsWith('catalog')?catalog:{id:job});},getDraft:()=>current,setDraft:v=>{applyCount++;current=structuredClone(v);},queueGameTracks:v=>queued=structuredClone(v)});
el('Folder').value=source.folder;el('Hash').value=h;
await el('Build').onclick();assert.equal(posts.length,0);assert.match(el('Status').textContent,/Load/);
await el('Inspect').onclick();assert.match(el('Status').textContent,/contacts fail/);assert.equal(el('Build').disabled,false);
el('Track').value='1';await el('Add').onclick();assert.match(el('Status').textContent,/eligible/);el('Track').value='0';await el('Add').onclick();await el('SaveActor').onclick();assert.deepEqual(editor.request(),request);
await el('Build').onclick();assert.deepEqual(posts.at(-1),['/api/native-transition-fits',request]);assert.equal(applyCount,0);
await el('Review').onclick();assert.match(el('Results').children[0].textContent,/native_contact_audit: fail/);assert.equal(el('Apply').disabled,false);assert.equal(applyCount,0);
await el('Apply').onclick();assert.deepEqual(current,draft);assert.deepEqual(queued.request,game);assert.equal(queued.actor_hashes.A.animation_index,4);assert.equal(applyCount,1);
await el('Review').onclick();await el('Resume').onclick();const resumed=editor.request();assert.deepEqual(resumed.resume_from,review.candidate_binding);assert.deepEqual(resumed.actors,request.actors);el('Penetration').value='100';assert.deepEqual(editor.request().geometry,request.geometry);
el('Label').value='';assert.throws(()=>editor.request(),/variant name/);el('Label').value='continued';await el('Add').onclick();assert.match(el('Status').textContent,/Continuation/);
// A changed scene while rechecking cannot silently replace the user's draft.
await el('Review').onclick();let resolve;waiting=new Promise(r=>resolve=r);const pending=el('Apply').onclick();current={schema:'newer draft'};resolve(review);await pending;assert.match(el('Status').textContent,/Scene or candidate changed/);assert.equal(applyCount,1);waiting=null;
// A different source while the catalog is in flight invalidates its reply.
waiting=new Promise(r=>resolve=r);const catalogPending=el('Inspect').onclick();el('Folder').value='different';el('Folder').oninput();resolve(catalog);await catalogPending;assert.match(el('Status').textContent,/selection changed/);assert.equal(el('Build').disabled,true);
const built=await readFile(new URL('../scripts/action-studio.html',import.meta.url),'utf8');assert(built.includes(html));assert(built.includes("import('/native-transition-fit-editor.mjs')"));assert(built.includes("import('/native-scene-transition-editor.mjs')"));
console.log('Bridge channel permissions, negative-result review, appended clip roles, exact downloads, continuation and stale explicit Apply passed offline.');
