import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {formatNativeContactDiagnostics as format,formatNativePlanting,nativeSupportAuditUrl} from '../scripts/native-contact-diagnostics.mjs';
assert.equal(nativeSupportAuditUrl({result_url:'/fitter.json',native_conversion_url:'/native.json'}),'/native.json');
assert.equal(nativeSupportAuditUrl({result_url:'/fitter.json'}),'/fitter.json');
const metric=(drift,speed)=>({supports:[{id:'left',candidate:{maximum_patch_vertex_tangential_drift_m:drift,maximum_patch_vertex_tangential_speed_m_s:speed}}]});
assert.equal(format(null),'');
assert.match(format({}),/measurements unavailable/);
const retained=format({retained_input:true,selected_contact_diagnostics:metric(.005,.03),proposal_contact_diagnostics:metric(.00488,.0286)});
assert.match(retained,/Selected native clip · left: maximum drift 5.00 mm, maximum tangential speed 30.00 mm\/s/);
assert.match(retained,/Converted proposal · left: maximum drift 4.88 mm/);
assert.match(retained,/Planted contact remains unverified/);
assert.doesNotMatch(retained,/approved|satisfied|certified|passed/);
assert.match(format({selected_contact_diagnostics:metric(0,0)}),/drift 0.00 mm/);
for(const value of [NaN,Infinity,-.001,'0.005',undefined]){
 assert.match(format({selected_contact_diagnostics:metric(value,.03)}),/measurements unavailable/);
 assert.match(format({selected_contact_diagnostics:metric(.005,value)}),/measurements unavailable/);
}
const html=await readFile(new URL('../scripts/native-support-viewer.html',import.meta.url),'utf8');
const viewer=await readFile(new URL('../scripts/native-support-viewer.mjs',import.meta.url),'utf8');
assert.equal([...html.matchAll(/id="contacts"/g)].length,1);
assert.match(viewer,/el\('contacts'\)\.textContent=contactText/);
assert.doesNotMatch(viewer,/el\('contacts'\)\.innerHTML/);
console.log('Native foot-drift formatting, retained/proposed distinction and unavailable metrics pass; no browser/GPU claim.');
const contact={id:'left',maximum_patch_anchor_error_m:.0005,maximum_patch_speed_m_s:.004999905137853149,maximum_anchor_error_m:.001,maximum_speed_m_s:.005,passed:true};
assert.equal(formatNativePlanting(null),'');
assert.match(formatNativePlanting({}),/unavailable/);
assert.match(formatNativePlanting({selected_audit:{contacts:[contact],passed:false}}),/contact gates pass.*0.5 \/ 1 mm.*4.99990514 \/ 5 mm\/s.*Full planting acceptance has not passed/);
assert.match(formatNativePlanting({selected_audit:{contacts:[contact],passed:true}}),/Animation quality remains unapproved/);
assert.match(formatNativePlanting({selected_audit:{contacts:[{...contact,maximum_patch_speed_m_s:.00500000073}],passed:false}}),/contact gates fail.*5.00000073/);
for(const value of [NaN,Infinity,-.1,'0.005',undefined])assert.match(formatNativePlanting({selected_audit:{contacts:[{...contact,maximum_patch_speed_m_s:value}]}}),/checks unavailable/);
assert.doesNotMatch(formatNativePlanting({selected_audit:{contacts:[{...contact,maximum_patch_speed_m_s:NaN}],passed:true}}),/All configured.*gates pass/);
assert.doesNotMatch(format({selected_planting_audit:{passed:true},selected_contact_diagnostics:metric(.0005,.004)}),/Planted contact remains unverified/);
console.log('Explicit source-anchor/speed limits, precision, unavailable data and separate full acceptance pass in offline formatting fixtures.');
