function createRigEventEditor({C,api,post,status,getContext,seek,pause,closeEditors,onJob}){
 let binding=null,markers=[],epoch=0,busy=false,reviewNotes=new Map();
 const safe=fn=>async()=>{try{await fn();}catch(e){status(e.message);}};
 function hide(){C('rigEventPanel').hidden=true;C('rigMappingPanel').hidden=false;}
 function reset(){epoch++;binding=null;reviewNotes.clear();hide();C('rigEvents').disabled=true;}
 function draw(){C('rigEventsList').replaceChildren();for(const e of markers){const row=document.createElement('div');row.className='rig-contact-row';const text=document.createElement('span');text.textContent=`${e.name} · frame ${e.frame} · ${e.confirmed?'timing authored':'needs timing review'}${reviewNotes.get(e.id)||''}`;const jump=document.createElement('button');jump.className='btn';jump.textContent='Go to '+e.name;jump.onclick=()=>{pause();seek(e.frame);};const remove=document.createElement('button');remove.className='btn';remove.textContent='Remove';remove.setAttribute('aria-label','Remove event '+e.name);remove.onclick=()=>{markers=markers.filter(v=>v!==e);draw();};row.append(text,jump);if(!e.confirmed){const review=document.createElement('button');review.className='btn';review.textContent='Confirm timing for '+e.name;review.onclick=()=>{e.confirmed=true;draw();};row.append(review);}row.append(remove);C('rigEventsList').append(row);}}
 C('rigEvents').onclick=safe(async()=>{const c=getContext();if(!c.job||c.variant==='repeated')throw Error('Select a finite clip or one cycle');pause();const token=++epoch;const data=await api('/api/rig-contact-source?'+new URLSearchParams({job:c.job.id,variant:c.variant}));if(token!==epoch||c.model!==getContext().model)return;binding=data;markers=(data.events?.events||[]).filter(e=>e.kind==='authored').map(e=>({id:e.id,name:e.name,frame:e.frame,confirmed:e.requires_review===false}));reviewNotes=new Map((data.events?.events||[]).map(e=>{const entries=Array.isArray(e.lineage)?e.lineage:[],shift=[...entries].reverse().find(v=>v.operation==='clip_retime'&&v.rounded_timing_requires_review&&Number.isFinite(v.timing_error_s));return [e.id,shift?` · Previous speed edit rounded ${shift.timing_error_s>0?'+':''}${(shift.timing_error_s*1000).toFixed(3)} ms`:'' ];}));closeEditors();C('rigMappingPanel').hidden=true;C('rigEventPanel').hidden=false;C('rigEventsLabel').value=('Markers · '+c.job.label).slice(0,160);C('rigEventFrame').value=c.frame;C('rigEventFrame').max=data.frames-1;C('rigEventsBinding').textContent=`${c.job.label} · ${c.variant} · ${data.frames} frames. Motion bytes are preserved.`;C('rigEventsStructural').textContent=`${(data.events?.events||[]).filter(e=>e.kind!=='authored').length} structural or legacy markers retained separately. To change an authored event, remove it and add its replacement.`;draw();});
 C('rigEventsClose').onclick=hide;C('rigEventCurrent').onclick=()=>C('rigEventFrame').value=getContext().frame;
 C('rigEventAdd').onclick=safe(()=>{if(!binding)throw Error('Open marker editing first');const name=C('rigEventName').value.trim(),frame=Number(C('rigEventFrame').value);if(!name||name.length>64||!Number.isInteger(frame)||frame<0||frame>=binding.frames)throw Error('Enter a name and a frame inside the clip');if(markers.length>=128)throw Error('At most 128 markers');markers.push({id:crypto.randomUUID(),name,frame,confirmed:true});markers.sort((a,b)=>a.frame-b.frame);draw();});
 C('rigEventsApply').onclick=safe(async()=>{const c=getContext();if(!binding||c.job?.id!==binding.job_id||c.variant!==binding.variant)throw Error('Reopen marker editing for this clip');onJob(await post('/api/rig-events',{schema:'strep-rig-events-v1',job:binding.job_id,variant:binding.variant,glb_sha256:binding.glb_sha256,label:C('rigEventsLabel').value,markers}));status('Saving event timing with the original motion unchanged.');});
 return {hide,reset,ready:()=>C('rigEvents').disabled=!getContext().result||getContext().result.kind==='neutral'||getContext().variant==='repeated',setBusy:b=>{busy=b;C('rigEventsApply').disabled=busy;}};
}
