  function bindControlCenter(){
    const showDetail=(title)=>{$('ccMain').hidden=true;$('ccDetail').hidden=false;$('ccDetailTitle').textContent=title;$('ccDetailBody').replaceChildren();$('ccBack').focus();animate($('ccDetail'),[{opacity:0,transform:'scale(.96)'},{opacity:1,transform:'none'}],180);return $('ccDetailBody');};
    const paragraph=(parent,text,className='')=>{const p=document.createElement('p');p.textContent=text;p.className=className;parent.append(p);return p;};
    const button=(parent,text,run)=>{const b=document.createElement('button');b.className='btn';b.textContent=text;b.onclick=run;parent.append(b);return b;};
    $('ccBack').onclick=()=>{$('ccMain').hidden=false;$('ccDetail').hidden=true;$('ccEdit').focus();};
    const systemText={wifi:['Wi-Fi','Network connections are managed by Windows. This web workspace cannot read your Wi-Fi network or change its settings.'],bluetooth:['Bluetooth','Bluetooth devices are managed by Windows. No device connection is changed by this control.'],airdrop:['AirDrop','AirDrop requires Apple devices. To share an animation from this workspace, use the export links in Preview.'],mirror:['Screen Mirroring','Display mirroring is managed by your operating system. For a larger animation view, use the green fullscreen control in Preview.'],sound:['Sound','These skeletal animation clips contain no audio. The Sound slider is unavailable; system volume is managed by Windows.']};
    document.querySelectorAll('[data-system-control]').forEach(b=>b.onclick=()=>{const [title,text]=systemText[b.dataset.systemControl],body=showDetail(title);paragraph(body,text);if(['airdrop','mirror','sound'].includes(b.dataset.systemControl))button(body,'Open Preview',()=>open('preview'));});
    $('ccFocus').onclick=()=>{const active=document.body.classList.toggle('workspace-focus');$('ccFocus').setAttribute('aria-pressed',String(active));};
    $('ccBrightness').oninput=e=>{const value=Number(e.target.value);document.documentElement.style.setProperty('--workspace-brightness',value/100);e.target.style.setProperty('--fill',((value-45)/55*100)+'%');};
    $('ccNext').onclick=()=>{const select=$('take');if(!select.options.length)return;select.selectedIndex=(select.selectedIndex+1)%select.options.length;select.dispatchEvent(new Event('change'));};
    const updatePlayback=()=>{const paused=$('play').textContent!=='Pause';$('ccPlay').innerHTML=paused?'<svg viewBox="0 0 24 24"><path d="m7 3 15 9-15 9z" fill="currentColor"/></svg>':'<svg viewBox="0 0 24 24"><path d="M7 4v16M17 4v16" stroke-width="5"/></svg>';$('ccPlay').setAttribute('aria-label',paused?'Play animation':'Pause animation');$('ccPlay').disabled=$('play').disabled;};
    new MutationObserver(updatePlayback).observe($('play'),{childList:true,attributes:true,attributeFilter:['disabled']});updatePlayback();
    $('ccEdit').onclick=()=>{const body=showDetail('Edit Controls');paragraph(body,'Desktop controls');for(const [label,value,run] of [['Dark Mode',dark,v=>dark=v],['Stage Manager',stageManager,v=>{stageManager=v;renderStage();}],['Automatically hide Dock',dockHide,v=>dockHide=v],['Reduce Motion',reduceMotion,v=>reduceMotion=v],['Reduce Transparency',reduceTransparency,v=>reduceTransparency=v]]){const row=document.createElement('label');row.textContent=label;const input=document.createElement('input');input.type='checkbox';input.checked=value;input.onchange=()=>{run(input.checked);applyTheme();};row.append(input);body.append(row);}button(body,'More Desktop Settings…',()=>open('settings'));};
    let elapsedMs=0,startedAt=null,timerInterval=null;
    function timer(){const body=showDetail('Stopwatch'),display=document.createElement('output');display.className='cc-stopwatch';body.append(display);const actions=document.createElement('div');actions.className='bar';body.append(actions);const render=()=>{const t=elapsedMs+(startedAt===null?0:performance.now()-startedAt);display.textContent=String(Math.floor(t/60000)).padStart(2,'0')+':'+String(Math.floor(t/1000)%60).padStart(2,'0')+'.'+Math.floor(t/100)%10;};const toggle=button(actions,startedAt===null?'Start':'Stop',()=>{if(startedAt===null)startedAt=performance.now();else{elapsedMs+=performance.now()-startedAt;startedAt=null;}toggle.textContent=startedAt===null?'Start':'Stop';render();});button(actions,'Reset',()=>{elapsedMs=0;if(startedAt!==null)startedAt=performance.now();render();});clearInterval(timerInterval);timerInterval=setInterval(()=>{if(!display.isConnected){clearInterval(timerInterval);return;}render();},100);render();}
    function calculator(){const body=showDetail('Calculator'),out=document.createElement('output');out.className='cc-calc-output';body.append(out);const keys=document.createElement('div');keys.className='cc-calc-keys';body.append(keys);let display='0',previous=null,op=null,fresh=true;const math=(a,b)=>op==='+'?a+b:op==='−'?a-b:op==='×'?a*b:b===0?NaN:a/b;const show=()=>out.textContent=display;for(const key of ['AC','±','%','÷','7','8','9','×','4','5','6','−','1','2','3','+','0','.','⌫','=']){const b=document.createElement('button');b.textContent=key;b.onclick=()=>{if(/^\d$/.test(key)||key==='.'){if(fresh||display==='Error'){display=key==='.'?'0.':key;fresh=false;}else if(display.length<13&&!(key==='.'&&display.includes('.')))display=display==='0'&&key!=='.'?key:display+key;}else if(key==='AC'){display='0';previous=null;op=null;fresh=true;}else if(key==='±')display=String(-Number(display));else if(key==='%')display=String(Number(display)/100);else if(key==='⌫')display=display.slice(0,-1)||'0';else{const number=Number(display);if(previous!==null&&op&&!fresh){const result=math(previous,number);display=Number.isFinite(result)?String(Number(result.toPrecision(10))):'Error';}previous=Number(display);op=key==='='?null:key;fresh=true;}show();};keys.append(b);}show();}
    document.querySelectorAll('[data-cc-utility]').forEach(b=>b.onclick=()=>b.dataset.ccUtility==='calculator'?calculator():timer());
    $('ccCapture').onclick=()=>{const body=showDetail('Preview Screenshot');if(!$('take').value){paragraph(body,'Select an animation in Preview first.');return;}try{const a=document.createElement('a');a.download='strep-preview.png';a.href=$('character').toDataURL('image/png');a.click();paragraph(body,'Requested a PNG download of the current animation preview.');button(body,'Open Preview',()=>open('preview'));}catch{paragraph(body,'The preview is not ready to capture. Open it and try again.');}};
  }
