// Audited development comparisons, kept separate from editable character-job selection.
void (async function correctionReview(){
 const C=id=>document.getElementById(id),panel=C('correctionReview');
 let catalog=null,selected=null,loaded=null,model=null,mixer=null,action=null,root=null,frame=0,clock=0,playing=false,token=0,catalogToken=0,previousRoot=null,last=performance.now(),renderer=null,controls=null,camera=null,scene=null,opening=false;
 const studies={half_floor:'/files/rig-jobs/half-floor-review-v1/catalog.json',iterations:'/files/rig-jobs/support-iterations-review-v1/catalog.json',midpoint_full:'/files/rig-jobs/midpoint-support-review-v2/catalog.json',midpoint:'/files/rig-jobs/midpoint-support-review-v1/catalog.json',support:'/files/rig-jobs/support-boundary-review-v1/catalog.json',angular:'/files/rig-jobs/correction-review-v2/catalog.json'};
 const canvas=C('correctionCanvas');
 let catalogHash=null,verifiedVersion=null;
 const feedback=setupDeveloperFeedback(()=>verifiedVersion&&selected&&catalogHash?{
  study_url:studies[C('correctionStudy').value],catalog_sha256:catalogHash,case_id:selected.id,
  variant:verifiedVersion.id,glb_url:verifiedVersion.glb,glb_sha256:verifiedVersion.sha256,
  frames:selected.frames,fps:selected.fps,prompt:selected.prompt,seed:selected.seed}:null,()=>frame);
 const say=text=>C('correctionStatus').textContent=text;
 function dispose(gltf){if(!gltf)return;gltf.scene.traverse(n=>{n.geometry?.dispose();for(const m of n.material?(Array.isArray(n.material)?n.material:[n.material]):[]){for(const value of Object.values(m))if(value?.isTexture)value.dispose();m.dispose();}});}
 async function setup(){
  if(renderer)return;
  const {OrbitControls}=await import('three/addons/controls/OrbitControls.js');
  scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(38,1,.01,100);renderer=new THREE.WebGLRenderer({canvas,antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0xe7eaed);renderer.outputColorSpace=THREE.SRGBColorSpace;
  scene.add(new THREE.HemisphereLight(0xf4f8ff,0x75818c,2.5));const light=new THREE.DirectionalLight(0xffffff,2.5);light.position.set(3,5,3);scene.add(light,new THREE.GridHelper(30,60,0xa1a9b1,0xc6cbd0));
  controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.minDistance=.15;controls.maxDistance=30;
 }
 function home(){if(!model)return;model.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(model,true),center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()),distance=Math.max(size.x,size.y,size.z,1)*1.9;controls.target.copy(center);camera.position.copy(center).add(new THREE.Vector3(distance*.8,distance*.3,distance));controls.update();}
 function seek(value){if(!mixer||!selected)return;frame=Math.max(0,Math.min(selected.frames-1,value));clock=frame/selected.fps;action.enabled=true;action.paused=false;mixer.setTime(clock);model.updateMatrixWorld(true);const position=root.getWorldPosition(new THREE.Vector3());if(previousRoot){const delta=new THREE.Vector3(position.x-previousRoot.x,0,position.z-previousRoot.z);camera.position.add(delta);controls.target.add(delta);}previousRoot=position;C('correctionFrame').value=frame;C('correctionTime').textContent=`${frame}/${selected.frames-1} · ${clock.toFixed(2)}s`;}
 function stop(){playing=false;C('correctionPlay').textContent='Play';}
 function link(label,url){const a=document.createElement('a');a.textContent=label;a.href=url;if(url.endsWith('.zip'))a.download='';return a;}
 async function showVersion(reset=false){
  verifiedVersion=null;feedback.refresh();C('correctionLandmarks').replaceChildren();
  stop();const version=selected.variants.find(v=>v.id===C('correctionVersion').value),current=++token,keepFrame=reset?0:frame;C('correctionPlay').disabled=true;C('correctionFrame').disabled=true;C('correctionReset').disabled=true;canvas.style.visibility='hidden';say('Loading and checking the saved motion…');C('correctionViewLabel').textContent='Loading…';C('correctionTime').textContent='Loading…';C('correctionMetrics').textContent='';C('correctionLinks').replaceChildren();
  try{
   const response=await fetch(version.glb);if(!response.ok)throw Error('Saved motion unavailable');const bytes=await response.arrayBuffer();const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),v=>v.toString(16).padStart(2,'0')).join('');if(digest!==version.sha256)throw Error('Saved motion has changed; review export rejected');
   const next=await new GLTFLoader().parseAsync(bytes,'');if(current!==token){dispose(next);return;}
   let nextRoot=null;next.scene.traverse(n=>{if(next.parser.associations.get(n)?.nodes===selected.root_node)nextRoot=n;});if(!nextRoot||!next.animations.length){dispose(next);throw Error('Saved motion is missing its root or animation');}
   if(loaded){mixer?.stopAllAction();mixer?.uncacheRoot(model);scene.remove(model);dispose(loaded);}loaded=next;model=next.scene;root=nextRoot;
   model.traverse(n=>{if(n.isMesh){for(const m of Array.isArray(n.material)?n.material:[n.material]){for(const v of Object.values(m))if(v?.isTexture)v.dispose();m.dispose();}n.material=new THREE.MeshStandardMaterial({color:0x9b9fa5,roughness:.8});n.frustumCulled=false;if(n.isSkinnedMesh)enableEightWeights(n);}});
   scene.add(model);mixer=new THREE.AnimationMixer(model);action=mixer.clipAction(next.animations[0]);action.setLoop(THREE.LoopOnce,1);action.clampWhenFinished=true;action.play();previousRoot=null;C('correctionFrame').max=selected.frames-1;seek(keepFrame);if(reset)home();
   C('correctionPlay').disabled=false;C('correctionFrame').disabled=false;C('correctionReset').disabled=false;canvas.style.visibility='visible';C('correctionViewLabel').textContent=version.label;say('Run outcome: '+selected.status_label+' · '+selected.blocks+' correction blocks');
   const m=version.metrics,mm=value=>Number.isFinite(value)?(value*1000).toFixed(2)+' mm':'not measured';const feet=m.support_peaks_m_s?` Predicted-support peak speed: ${Object.entries(m.support_peaks_m_s).map(([side,value])=>`${side.toLowerCase()} ${Number.isFinite(value)?value.toFixed(3)+' m/s':'no support samples'}`).join('; ')}.`:'';C('correctionMetrics').textContent=`This version: floor sample maximum ${mm(m.floor_depth_max_m)}; separate half-frame depth ${mm(m.half_frame_floor_depth_max_m)}. Root acceleration ${Number.isFinite(m.root_acceleration_max_m_s2)?m.root_acceleration_max_m_s2.toFixed(2)+' m/s²':'not measured'}.${feet}`;
   C('correctionLinks').replaceChildren(link('Current GLB',version.glb),link('Root track',version.root_track),link('Contact estimates',version.contacts),link('Comparison package',selected.package),link('Audit',selected.audit),link('License',selected.license));
   verifiedVersion=version;feedback.refresh();
   C('correctionLandmarks').replaceChildren(...(selected.review_landmarks||[]).map(point=>{const button=document.createElement('button');button.type='button';button.className='btn';button.textContent=point.label+' · '+point.frame;button.onclick=()=>{stop();seek(point.frame);};return button;}));
  }catch(error){if(current!==token)return;say(error.message);C('correctionViewLabel').textContent='Unable to load selected version';if(model){scene.remove(model);dispose(loaded);}loaded=model=mixer=action=root=null;}
 }
 async function choose(){selected=catalog.cases.find(c=>c.id===C('correctionCase').value);C('correctionVersion').replaceChildren(...selected.variants.map(v=>new Option(v.label,v.id)));C('correctionVersion').value=selected.default_variant;C('correctionVersion').disabled=false;C('correctionPrompt').textContent=selected.prompt+' Seed '+selected.seed+'.';C('correctionFailures').textContent=selected.review_note?('Selected result: '+selected.review_note):(selected.failed_checks.length?'Unresolved: '+selected.failed_checks.map(n=>n.startsWith('Left_')?'left-foot release acceleration':n.startsWith('Right_')?'right-foot release acceleration':n.replaceAll('_',' ')).join('; ')+'.':'');await showVersion(true);}
 async function loadStudy(){C('correctionLandmarks').replaceChildren();const request=++catalogToken;++token;stop();catalog=null;catalogHash=null;verifiedVersion=null;feedback.refresh();canvas.style.visibility='hidden';for(const id of ['correctionCase','correctionVersion','correctionPlay','correctionFrame','correctionReset'])C(id).disabled=true;say('Loading the selected study…');try{await setup();const response=await fetch(studies[C('correctionStudy').value]);if(!response.ok)throw Error('Correction review package unavailable');const bytes=await response.arrayBuffer();const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),v=>v.toString(16).padStart(2,'0')).join('');const next=JSON.parse(new TextDecoder().decode(bytes));if(request!==catalogToken)return;catalogHash=digest;if(!Array.isArray(next.cases)||!next.cases.length)throw Error('Correction study has no review cases');catalog=next;C('correctionCase').replaceChildren(...catalog.cases.map(c=>new Option(c.label,c.id)));C('correctionCase').disabled=false;await choose();}catch(error){if(request===catalogToken)say(error.message);}finally{if(request===catalogToken)opening=false;}}
 async function openReview(){if(!panel.open){stop();return;}if(catalog||opening)return;opening=true;await loadStudy();}
 panel.addEventListener('toggle',openReview);if(panel.open)void openReview();
 C('correctionStudy').onchange=()=>{opening=true;void loadStudy();};
 C('correctionCase').onchange=()=>choose().catch(e=>say(e.message));C('correctionVersion').onchange=()=>showVersion();C('correctionReset').onclick=home;
 C('correctionPlay').onclick=()=>{if(!mixer)return;if(frame>=selected.frames-1)seek(0);playing=!playing;C('correctionPlay').textContent=playing?'Pause':'Play';};C('correctionFrame').oninput=()=>{stop();seek(Number(C('correctionFrame').value));};
 function tick(time){const dt=Math.min((time-last)/1000,.1);last=time;const visible=renderer&&panel.open&&!panel.closest('.window').hidden;if(visible){if(playing&&mixer){const next=clock+dt;seek(Math.floor(next*selected.fps));clock=next;if(frame===selected.frames-1)stop();}const width=canvas.clientWidth,height=canvas.clientHeight;if(width&&height){const size=renderer.getSize(new THREE.Vector2());if(size.x!==width||size.y!==height){renderer.setSize(width,height,false);camera.aspect=width/height;camera.updateProjectionMatrix();}controls.update();renderer.render(scene,camera);}}requestAnimationFrame(tick);}
 requestAnimationFrame(tick);
})();
