"""Freeze an authored platform comparison; retain the unchanged actor baseline."""
import argparse
import copy
import shutil
from scipy.spatial.transform import Rotation
import numpy as np
from strep import ROOT,read,save,sha256,now


def prepare():
    out=ROOT/'reports/static-collider-v1';out.mkdir(exist_ok=False)
    source=ROOT/'reports/object-release-v2/seed-22-original/palm.json';bundle=read(source);scene=bundle['scene']
    for name,entry in scene['actors'].items():
        original=source.parent.parent/entry['preview_glb'];target=out/'actors'/name/'actor.glb';target.parent.mkdir(parents=True);shutil.copyfile(original,target)
        entry['preview_glb']=target.relative_to(out).as_posix()
    scene['id']='Platform release source'
    scene['objects']['platform']=dict(shape='box',size_m=[1.,.15,1.],keyframes=[dict(frame=0,translation_m=[.13215266870383957,.15,.7475388820239746],rotation_xyzw=Rotation.from_euler('y',25,degrees=True).as_quat().tolist())],trajectory_provenance='Explicit static test platform; authored geometry, not generated by the model')
    scene['review_note']='Existing seed-22 actor/object motion with an authored static platform. This source retains floating release and contact/body failures; scene placement is a diagnostic fixture.'
    from build_soma_preview import ASSET
    from scene_constraints import evaluate
    bundle['evaluation']=evaluate(scene,dict(np.load(ASSET,allow_pickle=False)))
    save(out/'source.json',bundle);shutil.copyfile(source.parent/'events.json',out/'events.json');shutil.copyfile(source.parent.parent/'SOMA-preview-LICENSE.txt',out/'SOMA-preview-LICENSE.txt')
    save(out/'manifest.json',dict(scenes=[dict(id='source',label='Release above a static platform · Source',variants=dict(palm='source.json'),review_note=scene['review_note'])]))
    save(out/'pipeline.json',dict(status='complete',scope='Authored source fixture ready; does not mean release study or quality is complete'))
    scripts=['object_release.py','release_geometry.py','object_geometry.py','godot_object_release.gd','release_colliders.py','scene_release_job.py']
    save(out/'protocol.json',dict(at=now(),original_source=str(source.relative_to(ROOT)),original_sha256=sha256(source),fixture_sha256=sha256(out/'source.json'),implementation={s:sha256(ROOT/'scripts'/s) for s in scripts},
        comparison=dict(source_url='/files/static-collider-v1/source.json',object='box',release_frame=121,mass_kg=3.,friction=.4,restitution=.2,modes=['floor_only','static_scene']),
        screens=dict(max_penetration_m=.01,final_linear_speed_m_s=.1,final_angular_speed_rad_s=.1),
        requirements=['Preserve all actors, original prefix and platform track','Save both floor-only and static-scene outcomes','Record per-collider contacts and independent SAT at physics rate','Verify export and actual engine playback','No human, training, actor collision or held-out release claim']))
    print(out)


if __name__=='__main__':prepare()
